name = "seo-copilot-api"
main = "./workers/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Account configuration (uncomment and set if needed)
# account_id = "c130aef39c1c8e06d07c94bbadbe2bd7"

[env.production]
workers_dev = true
# route = { pattern = "api.yoursite.com/*", zone_id = "your-zone-id" }

[env.development]
workers_dev = true

[vars]
ALLOWED_ORIGINS = "https://webflow.com,https://*.webflow-ext.com,https://*.webflow.io"

[limits]
memory_mb = 128
timeout_ms = 30000
cpu_ms = 50
