name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Workers
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
          
      - name: Setup pnpm store
        shell: bash
        run: |
          echo "STORE_PATH=/home/runner/.local/share/pnpm/store/v10" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
        
      # Add environment check
      - name: Check required secrets
        run: |
          [ -n "${{ secrets.VITE_WEBFLOW_CLIENT_ID }}" ] || exit 1
          [ -n "${{ secrets.CLOUDFLARE_API_TOKEN }}" ] || exit 1
          [ -n "${{ secrets.OPENAI_API_KEY }}" ] || exit 1
      
      - name: Build application
        run: pnpm build
        env:
          NODE_ENV: production
          VITE_WEBFLOW_EXTENSION: true
          USE_GPT_RECOMMENDATIONS: true
          VITE_WEBFLOW_API_KEY: ${{ secrets.VITE_WEBFLOW_API_KEY }}
          VITE_WEBFLOW_SITE_ID: ${{ secrets.VITE_WEBFLOW_SITE_ID }}
          VITE_WEBFLOW_CLIENT_ID: ${{ secrets.VITE_WEBFLOW_CLIENT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          
      - name: Validate build output
        run: |
          if [ ! -d "public" ]; then
            echo "Build output directory (public) is missing"
            exit 1
          fi
          
      - name: Create bundle archive
        run: zip -r bundle.zip public/

      - name: Upload bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: bundle.zip
          retention-days: 5
        
      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          echo "Starting direct Wrangler deployment..."
          
          # Create Cloudflare credentials file
          mkdir -p ~/.cloudflared
          cat > ~/.cloudflared/cert.pem << EOF
          api_token = ${{ secrets.CLOUDFLARE_API_TOKEN }}
          account_id = ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          EOF
          
          # Set proper permissions
          chmod 600 ~/.cloudflared/cert.pem
          
          # Install specific version of Wrangler globally
          npm install -g wrangler@3.22.1
          
          # Verify wrangler version
          wrangler --version
          
          # Set required environment variables
          export CLOUDFLARE_API_TOKEN="${{ secrets.CLOUDFLARE_API_TOKEN }}"
          export CLOUDFLARE_ACCOUNT_ID="${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
          export OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}"
          export WEBFLOW_CLIENT_SECRET="${{ secrets.WEBFLOW_CLIENT_SECRET }}"
          export WEBFLOW_CLIENT_ID="${{ secrets.WEBFLOW_CLIENT_ID }}"
          export WEBFLOW_REDIRECT_URI="${{ secrets.WEBFLOW_REDIRECT_URI }}"
          
          # Deploy with name flag
          CLOUDFLARE_API_TOKEN="${{ secrets.CLOUDFLARE_API_TOKEN }}" \
          CLOUDFLARE_ACCOUNT_ID="${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" \
          wrangler deploy workers/index.ts --name seo-copilot-api