name: Build and Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: Build Extension Bundle
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
          
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          # Configure npm/pnpm with retry settings to avoid rate limiting issues
          echo "registry=https://registry.npmjs.org/" > .npmrc
          echo "fetch-retries=5" >> .npmrc
          echo "fetch-retry-factor=5" >> .npmrc
          echo "fetch-retry-mintimeout=15000" >> .npmrc
          echo "fetch-retry-maxtimeout=120000" >> .npmrc
          
          # Use pnpm with no frozen lockfile to allow updates
          pnpm install --no-frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
      # Add environment check
      - name: Check required secrets
        run: |
          [ -n "${{ secrets.VITE_WEBFLOW_CLIENT_ID }}" ] || exit 1
          [ -n "${{ secrets.OPENAI_API_KEY }}" ] || exit 1
      
      - name: Build application
        run: pnpm build
        env:
          NODE_ENV: production
          VITE_WEBFLOW_EXTENSION: true
          USE_GPT_RECOMMENDATIONS: true
          VITE_WEBFLOW_API_KEY: ${{ secrets.VITE_WEBFLOW_API_KEY }}
          VITE_WEBFLOW_SITE_ID: ${{ secrets.VITE_WEBFLOW_SITE_ID }}
          VITE_WEBFLOW_CLIENT_ID: ${{ secrets.VITE_WEBFLOW_CLIENT_ID }}
          
      - name: Validate build output
        run: |
          if [ ! -d "public" ]; then
            echo "Build output directory (public) is missing"
            exit 1
          fi
          
      - name: Create bundle archive
        run: zip -r bundle.zip public/

      - name: Upload bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: bundle.zip
          retention-days: 5